// Code generated by genmsg. DO NOT EDIT.
//
// 契约唯一源：docs/spec/60-reference/61-messages.schema.json
//（= docs/spec/60-reference/61-消息一览.md，消息面唯一准则）。
// 重新生成：go run src/tools/genmsg

package msgkeys

// ── 主题常量（61 topic，逐条镜像）──
const (
	TopicGuiInitData              = "gui.init-data"
	TopicAgentWizard              = "agent-wizard"
	TopicGuiUiSave                = "gui.ui.save"
	TopicGuiWindowStatus          = "gui.window.status"
	TopicGuiWindowOpenChat        = "gui.window.open-chat"
	TopicGuiWindowList            = "gui.window.list"
	TopicGuiWindowClosed          = "gui.window.closed"
	TopicGuiWindowSetTitle        = "gui.window.set-title"
	TopicGuiDirOpenDialog         = "gui.dir.open-dialog"
	TopicGuiDirOpen               = "gui.dir.open"
	TopicGuiRecentList            = "gui.recent.list"
	TopicGuiRecentRemove          = "gui.recent.remove"
	TopicGuiConsoleOpen           = "gui.console.open"
	TopicGuiVcsInfo               = "gui.vcs.info"
	TopicGuiReveal                = "gui.reveal"
	TopicGuiOpenWith              = "gui.open-with"
	TopicGuiSearch                = "gui.search"
	TopicGuiCapture               = "gui.capture"
	TopicGuiUpload                = "gui.upload"
	TopicGuiDevtoolsOpen          = "gui.devtools.open"
	TopicGuiPickExecutable        = "gui.pick-executable"
	TopicGuiFileSave              = "gui.file.save"
	TopicGuiToolchainDetect       = "gui.toolchain.detect"
	TopicGuiSystemBuiltins        = "gui.system.builtins"
	TopicGuiPromptOptimise        = "gui.prompt-optimise"
	TopicGuiPromptVars            = "gui.prompt-vars"
	TopicOptimizeToken            = "optimize-token"
	TopicOptimizeDone             = "optimize-done"
	TopicOptimizeError            = "optimize-error"
	TopicWindowMaximizedChanged   = "window-maximized-changed"
	TopicLlmTestConnection        = "llm.test-connection"
	TopicMemoryFlush              = "memory.flush"
	TopicFilesysList              = "filesys.list"
	TopicFilesysContent           = "filesys.content"
	TopicFilesysCreate            = "filesys.create"
	TopicFilesysMkdir             = "filesys.mkdir"
	TopicFilesysRemove            = "filesys.remove"
	TopicFilesysRename            = "filesys.rename"
	TopicFilesysCopy              = "filesys.copy"
	TopicFilesysWatch             = "filesys.watch"
	TopicFilesysUnwatch           = "filesys.unwatch"
	TopicFilesysChanged           = "filesys.changed"
	TopicFilesysWatchError        = "filesys.watch-error"
	TopicDataUserConfigList       = "data-user-config-list"
	TopicDataUserConfigLoad       = "data-user-config-load"
	TopicDataUserConfigSave       = "data-user-config-save"
	TopicDataUserConfigDelete     = "data-user-config-delete"
	TopicDataUserConfigChanged    = "data-user-config-changed"
	TopicDataUserConfigRefresh    = "data-user-config-refresh"
	TopicDataPrjConfigList        = "data-prj-config-list"
	TopicDataPrjConfigLoad        = "data-prj-config-load"
	TopicDataPrjConfigSave        = "data-prj-config-save"
	TopicDataPrjConfigDelete      = "data-prj-config-delete"
	TopicDataPrjConfigRefresh     = "data-prj-config-refresh"
	TopicDataPrjSecurityList      = "data-prj-security-list"
	TopicDataPrjSecurityLoad      = "data-prj-security-load"
	TopicDataPrjSecuritySave      = "data-prj-security-save"
	TopicDataPrjSecurityDelete    = "data-prj-security-delete"
	TopicDataPrjSecurityRefresh   = "data-prj-security-refresh"
	TopicDataPromptList           = "data-prompt-list"
	TopicDataPromptLoad           = "data-prompt-load"
	TopicDataPromptSave           = "data-prompt-save"
	TopicDataPromptDelete         = "data-prompt-delete"
	TopicDataPromptRefresh        = "data-prompt-refresh"
	TopicDataScenarioList         = "data-scenario-list"
	TopicDataScenarioLoad         = "data-scenario-load"
	TopicDataScenarioSave         = "data-scenario-save"
	TopicDataScenarioDelete       = "data-scenario-delete"
	TopicDataScenarioRefresh      = "data-scenario-refresh"
	TopicDataMcpList              = "data-mcp-list"
	TopicDataMcpLoad              = "data-mcp-load"
	TopicDataMcpSave              = "data-mcp-save"
	TopicDataMcpDelete            = "data-mcp-delete"
	TopicDataMcpRefresh           = "data-mcp-refresh"
	TopicDataMemoryList           = "data-memory-list"
	TopicDataMemoryRead           = "data-memory-read"
	TopicDataMemorySave           = "data-memory-save"
	TopicDataMemoryDelete         = "data-memory-delete"
	TopicDataMemoryRefresh        = "data-memory-refresh"
	TopicDataMemoryExtractLoad    = "data-memory-extract-load"
	TopicDataMemoryExtractSave    = "data-memory-extract-save"
	TopicDataMemoryExtractDelete  = "data-memory-extract-delete"
	TopicDataFilelistList         = "data-filelist-list"
	TopicDataFilelistPut          = "data-filelist-put"
	TopicDataFilelistDel          = "data-filelist-del"
	TopicConfigRefresh            = "config-refresh"
	TopicDataSessionList          = "data-session-list"
	TopicDataSessionGet           = "data-session-get"
	TopicDataSessionHistory       = "data-session-history"
	TopicDataSessionContent       = "data-session-content"
	TopicDataSessionLatest        = "data-session-latest"
	TopicDataSessionTitle         = "data-session-title"
	TopicDataSessionTitleChanged  = "data-session-title-changed"
	TopicDataSessionDelete        = "data-session-delete"
	TopicDataSessionActiveSet     = "data-session-active-set"
	TopicDataSessionActiveGet     = "data-session-active-get"
	TopicDataSessionEnsureSession = "data-session-ensure-session"
	TopicDataSessionEnsureTurn    = "data-session-ensure-turn"
	TopicDataSessionAppendMessage = "data-session-append-message"
	TopicDataSessionSetSummary    = "data-session-set-summary"
	TopicDataSessionCompleteTurn  = "data-session-complete-turn"
	TopicDataSessionCleanupStale  = "data-session-cleanup-stale"
	TopicDataSessionLoadMessages  = "data-session-load-messages"
	TopicDataSessionContext       = "data-session-context"
	TopicDataSnapshotGet          = "data-snapshot-get"
	TopicDataSnapshotSet          = "data-snapshot-set"
	TopicDataKnowledgeRoot        = "data-knowledge-root"
	TopicDataKnowledgeList        = "data-knowledge-list"
	TopicDataKnowledgeRead        = "data-knowledge-read"
	TopicDataKnowledgeSave        = "data-knowledge-save"
	TopicDataKnowledgeCreate      = "data-knowledge-create"
	TopicDataKnowledgeDelete      = "data-knowledge-delete"
	TopicDataKnowledgeRename      = "data-knowledge-rename"
	TopicDataKnowledgeMkdir       = "data-knowledge-mkdir"
	TopicDataKnowledgeRmdir       = "data-knowledge-rmdir"
	TopicDataKnowledgeRenameDir   = "data-knowledge-rename-dir"
	TopicDataTasktreeList         = "data-tasktree-list"
	TopicDataTasktreeTasks        = "data-tasktree-tasks"
	TopicDataTasktreeDelete       = "data-tasktree-delete"
	TopicDataTasktreeUpsert       = "data-tasktree-upsert"
	TopicTaskDeleted              = "task-deleted"
	TopicDataIndexIgnored         = "data-index-ignored"
	TopicInstanceClaim            = "instance-claim"
	TopicInstanceRegister         = "instance-register"
	TopicInstanceHeartbeat        = "instance-heartbeat"
	TopicInstanceExit             = "instance-exit"
	TopicLlmStart                 = "llm-start"
	TopicLlmSend                  = "llm-send"
	TopicLlmCancel                = "llm-cancel"
	TopicAskUserReply             = "ask-user-reply"
	TopicToolRetry                = "tool-retry"
	TopicTaskStop                 = "task-stop"
	TopicTaskBackground           = "task-background"
	TopicPromptOptimise           = "prompt-optimise"
	TopicTaskVerify               = "task-verify"
	TopicAgentWizardProbe         = "agent-wizard-probe"
	TopicAgentWizardCompose       = "agent-wizard-compose"
	TopicAgentWizardGenerate      = "agent-wizard-generate"
	TopicAgentWizardSkip          = "agent-wizard-skip"
	TopicLlmSimple                = "llm-simple"
	TopicLoginRegister            = "login-register"
	TopicLoginIn                  = "login-in"
	TopicLoginOut                 = "login-out"
	TopicSessionReceive           = "session-receive"
	TopicSessionComplete          = "session-complete"
	TopicSessionCompress          = "session-compress"
	TopicSessionAsk               = "session-ask"
	TopicSessionTurnStart         = "session-turn-start"
	TopicSessionNew               = "session-new"
	TopicTaskStarted              = "task-started"
	TopicTaskUpdated              = "task-updated"
	TopicTaskDone                 = "task-done"
	TopicServerStarting           = "server-starting"
	TopicPromptOptimised          = "prompt-optimised"
	TopicToolNotify               = "tool-notify"
	TopicMcpToolsList             = "mcp-tools-list"
	TopicMcpToolsCall             = "mcp-tools-call"
	TopicMcpToolsWait             = "mcp-tools-wait"
	TopicMcpToolsRegister         = "mcp-tools-register"
	TopicMcpToolsUnregister       = "mcp-tools-unregister"
	TopicMcpPromptsList           = "mcp-prompts-list"
	TopicMcpPromptsGet            = "mcp-prompts-get"
	TopicMcpPromptsRegister       = "mcp-prompts-register"
	TopicMcpPromptsUnregister     = "mcp-prompts-unregister"
	TopicMcpResourcesList         = "mcp-resources-list"
	TopicMcpResourcesRead         = "mcp-resources-read"
	TopicMcpResourcesRegister     = "mcp-resources-register"
	TopicMcpResourcesUnregister   = "mcp-resources-unregister"
	TopicMcpServersList           = "mcp-servers-list"
	TopicMcpServersGet            = "mcp-servers-get"
	TopicMcpServersRegister       = "mcp-servers-register"
	TopicMcpServersUnregister     = "mcp-servers-unregister"
	TopicMcpGatewayCheck          = "mcp-gateway-check"
	TopicMcpGatewayReload         = "mcp-gateway-reload"
	TopicMcpTasksReport           = "mcp-tasks-report"
	TopicMcpToolsTimeout          = "mcp-tools-timeout"
	TopicMcpGatewayChanged        = "mcp-gateway-changed"
	TopicHistoryPreToolHook       = "history-pre-tool-hook"
	TopicCodegraphToolCall        = "codegraph-tool-call"
	TopicVftsToolCall             = "vfts-tool-call"
	TopicVftsDictGet              = "vfts.dict.get"
	TopicVftsDictSet              = "vfts.dict.set"
	TopicVftsReindex              = "vfts.reindex"
	TopicProjectConfigOpen        = "project-config-open"
	TopicPreviewTabOpen           = "preview-tab-open"
)

// ── 客户端 topic 常量（schema clientTopic；前端 type ↔ 总线相对主题 的键；JS 侧 = MsgClientTopics）──
const (
	MsgClientTopicsToolsList     = "tools-list"
	MsgClientTopicsMcpToolsWait  = "mcp-tools-wait"
	MsgClientTopicsPromptsList   = "prompts-list"
	MsgClientTopicsResourcesList = "resources-list"
)

// ── 键常量（按主题/侧分组；命名 = <主题><侧><键>）──
const (
	// gui.init-data · result
	GuiInitDataResultExpandedKeys   = "expandedKeys"
	GuiInitDataResultFiletreeWidth  = "filetreeWidth"
	GuiInitDataResultLayout         = "layout"
	GuiInitDataResultLogDir         = "logDir"
	GuiInitDataResultOpenedFile     = "openedFile"
	GuiInitDataResultOpenedFiles    = "openedFiles"
	GuiInitDataResultSelectedKey    = "selectedKey"
	GuiInitDataResultTreeData       = "treeData"
	GuiInitDataResultUi             = "ui"
	GuiInitDataResultWizardRequired = "wizard_required"
	GuiInitDataResultWorkDir        = "workDir"

	// agent-wizard · event
	AgentWizardEventReason   = "reason"
	AgentWizardEventSpecPath = "spec_path"
	AgentWizardEventWorkDir  = "work_dir"

	// gui.ui.save · payload
	GuiUiSavePayloadFiletree    = "filetree"
	GuiUiSavePayloadLayout      = "layout"
	GuiUiSavePayloadOpenedFiles = "opened_files"
	GuiUiSavePayloadUi          = "ui"
	GuiUiSavePayloadWindow      = "window"

	// gui.ui.save · result
	GuiUiSaveResultOk = "ok"

	// gui.window.status · payload
	GuiWindowStatusPayloadCommand = "command"

	// gui.window.status · result
	GuiWindowStatusResultMaximized = "maximized"
	GuiWindowStatusResultMinimized = "minimized"

	// gui.window.open-chat · payload
	GuiWindowOpenChatPayloadSessionId = "session_id"

	// gui.window.open-chat · result
	GuiWindowOpenChatResultActivated = "activated"
	GuiWindowOpenChatResultOk        = "ok"
	GuiWindowOpenChatResultWindowId  = "window_id"

	// gui.window.list · result
	GuiWindowListResultWindows = "windows"

	// gui.window.closed · event
	GuiWindowClosedEventSessionId = "session_id"
	GuiWindowClosedEventWindowId  = "window_id"

	// gui.window.set-title · payload
	GuiWindowSetTitlePayloadTitle = "title"

	// gui.window.set-title · result
	GuiWindowSetTitleResultOk = "ok"

	// gui.dir.open-dialog · result
	GuiDirOpenDialogResultPath = "path"

	// gui.dir.open · payload
	GuiDirOpenPayloadPath = "path"

	// gui.dir.open · result
	GuiDirOpenResultOk = "ok"

	// gui.recent.list · result
	GuiRecentListResultDirs = "dirs"

	// gui.recent.remove · payload
	GuiRecentRemovePayloadPath = "path"

	// gui.recent.remove · result
	GuiRecentRemoveResultOk = "ok"

	// gui.console.open · payload
	GuiConsoleOpenPayloadPath = "path"

	// gui.console.open · result
	GuiConsoleOpenResultOk = "ok"

	// gui.vcs.info · payload
	GuiVcsInfoPayloadPath = "path"

	// gui.vcs.info · result
	GuiVcsInfoResultGit          = "git"
	GuiVcsInfoResultGitInstalled = "gitInstalled"
	GuiVcsInfoResultSvn          = "svn"

	// gui.reveal · payload
	GuiRevealPayloadPath = "path"

	// gui.reveal · result
	GuiRevealResultOk = "ok"

	// gui.open-with · payload
	GuiOpenWithPayloadPath = "path"

	// gui.open-with · result
	GuiOpenWithResultOk = "ok"

	// gui.search · payload
	GuiSearchPayloadQuery = "query"

	// gui.search · result
	GuiSearchResultResults = "results"

	// gui.capture · result
	GuiCaptureResultB64    = "b64"
	GuiCaptureResultFileId = "file_id"
	GuiCaptureResultName   = "name"
	GuiCaptureResultPath   = "path"
	GuiCaptureResultSize   = "size"
	GuiCaptureResultUrl    = "url"

	// gui.upload · payload
	GuiUploadPayloadData = "data"
	GuiUploadPayloadKind = "kind"
	GuiUploadPayloadName = "name"

	// gui.upload · result
	GuiUploadResultFileId = "file_id"
	GuiUploadResultName   = "name"
	GuiUploadResultPath   = "path"
	GuiUploadResultUrl    = "url"

	// gui.pick-executable · result
	GuiPickExecutableResultPath = "path"

	// gui.file.save · payload
	GuiFileSavePayloadContent = "content"
	GuiFileSavePayloadMode    = "mode"
	GuiFileSavePayloadName    = "name"

	// gui.file.save · result
	GuiFileSaveResultPath = "path"

	// gui.toolchain.detect · result
	GuiToolchainDetectResultTools = "tools"

	// gui.system.builtins · result
	GuiSystemBuiltinsResultMcpServers = "mcpServers"

	// gui.prompt-optimise · payload
	GuiPromptOptimisePayloadPrompt  = "prompt"
	GuiPromptOptimisePayloadTitle   = "title"
	GuiPromptOptimisePayloadUseCase = "useCase"

	// gui.prompt-optimise · result
	GuiPromptOptimiseResultOk      = "ok"
	GuiPromptOptimiseResultStarted = "started"

	// gui.prompt-vars · result
	GuiPromptVarsResultGroups = "groups"

	// optimize-token · event
	OptimizeTokenEventContent = "content"

	// optimize-done · event
	OptimizeDoneEventPrompt = "prompt"

	// optimize-error · event
	OptimizeErrorEventCode    = "code"
	OptimizeErrorEventMessage = "message"
	OptimizeErrorEventName    = "name"
	OptimizeErrorEventStatus  = "status"

	// window-maximized-changed · event
	WindowMaximizedChangedEventInstanceId = "instance_id"
	WindowMaximizedChangedEventMaximized  = "maximized"

	// llm.test-connection · payload
	LlmTestConnectionPayloadApiKey     = "apiKey"
	LlmTestConnectionPayloadBaseUrl    = "baseUrl"
	LlmTestConnectionPayloadInstanceId = "instance_id"
	LlmTestConnectionPayloadModel      = "model"
	LlmTestConnectionPayloadProtocol   = "protocol"

	// llm.test-connection · result
	LlmTestConnectionResultError     = "error"
	LlmTestConnectionResultLatencyMs = "latency_ms"
	LlmTestConnectionResultModelEcho = "model_echo"
	LlmTestConnectionResultOk        = "ok"

	// memory.flush · payload
	MemoryFlushPayloadInstanceId = "instance_id"
	MemoryFlushPayloadSession    = "session"

	// memory.flush · result
	MemoryFlushResultOk      = "ok"
	MemoryFlushResultQueued  = "queued"
	MemoryFlushResultReason  = "reason"
	MemoryFlushResultSession = "session"

	// filesys.list · payload
	FilesysListPayloadLimit   = "limit"
	FilesysListPayloadPath    = "path"
	FilesysListPayloadStart   = "start"
	FilesysListPayloadWorkDir = "work_dir"

	// filesys.list · result
	FilesysListResultChildren = "children"
	FilesysListResultIsDir    = "is_dir"
	FilesysListResultPath     = "path"

	// filesys.content · payload
	FilesysContentPayloadPath    = "path"
	FilesysContentPayloadWorkDir = "work_dir"

	// filesys.content · result
	FilesysContentResultContent   = "content"
	FilesysContentResultKind      = "kind"
	FilesysContentResultPath      = "path"
	FilesysContentResultTruncated = "truncated"

	// filesys.create · payload
	FilesysCreatePayloadContent = "content"
	FilesysCreatePayloadDir     = "dir"
	FilesysCreatePayloadName    = "name"
	FilesysCreatePayloadWorkDir = "work_dir"

	// filesys.create · result
	FilesysCreateResultOk   = "ok"
	FilesysCreateResultPath = "path"

	// filesys.mkdir · payload
	FilesysMkdirPayloadDir     = "dir"
	FilesysMkdirPayloadName    = "name"
	FilesysMkdirPayloadWorkDir = "work_dir"

	// filesys.mkdir · result
	FilesysMkdirResultOk   = "ok"
	FilesysMkdirResultPath = "path"

	// filesys.remove · payload
	FilesysRemovePayloadPath    = "path"
	FilesysRemovePayloadWorkDir = "work_dir"

	// filesys.remove · result
	FilesysRemoveResultOk = "ok"

	// filesys.rename · payload
	FilesysRenamePayloadNewName   = "new_name"
	FilesysRenamePayloadOverwrite = "overwrite"
	FilesysRenamePayloadPath      = "path"
	FilesysRenamePayloadWorkDir   = "work_dir"

	// filesys.rename · result
	FilesysRenameResultOk   = "ok"
	FilesysRenameResultPath = "path"

	// filesys.copy · payload
	FilesysCopyPayloadDestDir   = "dest_dir"
	FilesysCopyPayloadNewName   = "new_name"
	FilesysCopyPayloadOverwrite = "overwrite"
	FilesysCopyPayloadPath      = "path"
	FilesysCopyPayloadWorkDir   = "work_dir"

	// filesys.copy · result
	FilesysCopyResultOk   = "ok"
	FilesysCopyResultPath = "path"

	// filesys.watch · payload
	FilesysWatchPayloadPath      = "path"
	FilesysWatchPayloadRecursive = "recursive"
	FilesysWatchPayloadWorkDir   = "work_dir"

	// filesys.unwatch · payload
	FilesysUnwatchPayloadPath    = "path"
	FilesysUnwatchPayloadWorkDir = "work_dir"

	// filesys.changed · event
	FilesysChangedEventChildren   = "children"
	FilesysChangedEventInstanceId = "instance_id"
	FilesysChangedEventOperation  = "operation"
	FilesysChangedEventPath       = "path"
	FilesysChangedEventWorkDir    = "work_dir"

	// filesys.watch-error · event
	FilesysWatchErrorEventError      = "error"
	FilesysWatchErrorEventInstanceId = "instance_id"
	FilesysWatchErrorEventPath       = "path"
	FilesysWatchErrorEventWorkDir    = "work_dir"

	// data-user-config-list · result
	DataUserConfigListResultList = "list"

	// data-user-config-load · result
	DataUserConfigLoadResultData = "data"

	// data-user-config-save · payload
	DataUserConfigSavePayloadData = "data"

	// data-user-config-save · result
	DataUserConfigSaveResultId = "id"
	DataUserConfigSaveResultOk = "ok"

	// data-user-config-delete · payload
	DataUserConfigDeletePayloadId  = "id"
	DataUserConfigDeletePayloadKey = "key"

	// data-user-config-delete · result
	DataUserConfigDeleteResultId = "id"
	DataUserConfigDeleteResultOk = "ok"

	// data-user-config-changed · event
	DataUserConfigChangedEventData = "data"

	// data-user-config-refresh · event
	DataUserConfigRefreshEventId         = "id"
	DataUserConfigRefreshEventIds        = "ids"
	DataUserConfigRefreshEventInstanceId = "instance_id"
	DataUserConfigRefreshEventList       = "list"
	DataUserConfigRefreshEventOp         = "op"

	// data-prj-config-list · result
	DataPrjConfigListResultList = "list"

	// data-prj-config-load · payload
	DataPrjConfigLoadPayloadId = "id"

	// data-prj-config-load · result
	DataPrjConfigLoadResultData = "data"

	// data-prj-config-save · payload
	DataPrjConfigSavePayloadData = "data"

	// data-prj-config-save · result
	DataPrjConfigSaveResultId = "id"
	DataPrjConfigSaveResultOk = "ok"

	// data-prj-config-delete · payload
	DataPrjConfigDeletePayloadId = "id"

	// data-prj-config-delete · result
	DataPrjConfigDeleteResultOk = "ok"

	// data-prj-config-refresh · event
	DataPrjConfigRefreshEventId         = "id"
	DataPrjConfigRefreshEventIds        = "ids"
	DataPrjConfigRefreshEventInstanceId = "instance_id"
	DataPrjConfigRefreshEventList       = "list"
	DataPrjConfigRefreshEventOp         = "op"

	// data-prj-security-list · result
	DataPrjSecurityListResultList = "list"

	// data-prj-security-load · payload
	DataPrjSecurityLoadPayloadId = "id"

	// data-prj-security-load · result
	DataPrjSecurityLoadResultData = "data"

	// data-prj-security-save · payload
	DataPrjSecuritySavePayloadData = "data"

	// data-prj-security-save · result
	DataPrjSecuritySaveResultId = "id"
	DataPrjSecuritySaveResultOk = "ok"

	// data-prj-security-delete · payload
	DataPrjSecurityDeletePayloadId = "id"

	// data-prj-security-delete · result
	DataPrjSecurityDeleteResultOk = "ok"

	// data-prj-security-refresh · event
	DataPrjSecurityRefreshEventId         = "id"
	DataPrjSecurityRefreshEventIds        = "ids"
	DataPrjSecurityRefreshEventInstanceId = "instance_id"
	DataPrjSecurityRefreshEventList       = "list"
	DataPrjSecurityRefreshEventOp         = "op"

	// data-prompt-list · result
	DataPromptListResultList = "list"

	// data-prompt-load · payload
	DataPromptLoadPayloadId = "id"

	// data-prompt-load · result
	DataPromptLoadResultData = "data"

	// data-prompt-save · payload
	DataPromptSavePayloadData = "data"

	// data-prompt-save · result
	DataPromptSaveResultId = "id"
	DataPromptSaveResultOk = "ok"

	// data-prompt-delete · payload
	DataPromptDeletePayloadId = "id"

	// data-prompt-delete · result
	DataPromptDeleteResultOk = "ok"

	// data-prompt-refresh · event
	DataPromptRefreshEventId         = "id"
	DataPromptRefreshEventIds        = "ids"
	DataPromptRefreshEventInstanceId = "instance_id"
	DataPromptRefreshEventList       = "list"
	DataPromptRefreshEventOp         = "op"

	// data-scenario-list · result
	DataScenarioListResultList = "list"
	DataScenarioListResultOk   = "ok"

	// data-scenario-load · payload
	DataScenarioLoadPayloadId    = "id"
	DataScenarioLoadPayloadLevel = "level"

	// data-scenario-load · result
	DataScenarioLoadResultData = "data"
	DataScenarioLoadResultOk   = "ok"

	// data-scenario-save · payload
	DataScenarioSavePayloadData = "data"

	// data-scenario-save · result
	DataScenarioSaveResultId = "id"
	DataScenarioSaveResultOk = "ok"

	// data-scenario-delete · payload
	DataScenarioDeletePayloadId    = "id"
	DataScenarioDeletePayloadLevel = "level"

	// data-scenario-delete · result
	DataScenarioDeleteResultOk = "ok"

	// data-scenario-refresh · event
	DataScenarioRefreshEventId         = "id"
	DataScenarioRefreshEventIds        = "ids"
	DataScenarioRefreshEventInstanceId = "instance_id"
	DataScenarioRefreshEventList       = "list"
	DataScenarioRefreshEventOp         = "op"

	// data-mcp-list · result
	DataMcpListResultList = "list"

	// data-mcp-load · payload
	DataMcpLoadPayloadId    = "id"
	DataMcpLoadPayloadLevel = "level"
	DataMcpLoadPayloadName  = "name"

	// data-mcp-load · result
	DataMcpLoadResultData = "data"

	// data-mcp-save · payload
	DataMcpSavePayloadData     = "data"
	DataMcpSavePayloadOldLevel = "old_level"
	DataMcpSavePayloadOldName  = "old_name"

	// data-mcp-save · result
	DataMcpSaveResultName = "name"
	DataMcpSaveResultOk   = "ok"

	// data-mcp-delete · payload
	DataMcpDeletePayloadId    = "id"
	DataMcpDeletePayloadLevel = "level"
	DataMcpDeletePayloadName  = "name"

	// data-mcp-delete · result
	DataMcpDeleteResultOk = "ok"

	// data-mcp-refresh · event
	DataMcpRefreshEventId         = "id"
	DataMcpRefreshEventIds        = "ids"
	DataMcpRefreshEventInstanceId = "instance_id"
	DataMcpRefreshEventList       = "list"
	DataMcpRefreshEventOp         = "op"

	// data-memory-list · result
	DataMemoryListResultList = "list"

	// data-memory-read · payload
	DataMemoryReadPayloadCategory = "category"

	// data-memory-read · result
	DataMemoryReadResultData = "data"

	// data-memory-save · payload
	DataMemorySavePayloadData = "data"

	// data-memory-save · result
	DataMemorySaveResultId = "id"
	DataMemorySaveResultOk = "ok"

	// data-memory-delete · payload
	DataMemoryDeletePayloadData = "data"

	// data-memory-delete · result
	DataMemoryDeleteResultId = "id"
	DataMemoryDeleteResultOk = "ok"

	// data-memory-refresh · event
	DataMemoryRefreshEventId         = "id"
	DataMemoryRefreshEventIds        = "ids"
	DataMemoryRefreshEventInstanceId = "instance_id"
	DataMemoryRefreshEventList       = "list"
	DataMemoryRefreshEventOp         = "op"

	// data-memory-extract-load · payload
	DataMemoryExtractLoadPayloadCategory  = "category"
	DataMemoryExtractLoadPayloadSessionId = "session_id"

	// data-memory-extract-load · result
	DataMemoryExtractLoadResultList = "list"

	// data-memory-extract-save · payload
	DataMemoryExtractSavePayloadData = "data"

	// data-memory-extract-save · result
	DataMemoryExtractSaveResultId = "id"
	DataMemoryExtractSaveResultOk = "ok"

	// data-memory-extract-delete · payload
	DataMemoryExtractDeletePayloadData = "data"

	// data-memory-extract-delete · result
	DataMemoryExtractDeleteResultOk = "ok"

	// data-filelist-list · payload
	DataFilelistListPayloadLimit  = "limit"
	DataFilelistListPayloadOffset = "offset"
	DataFilelistListPayloadPrefix = "prefix"

	// data-filelist-list · result
	DataFilelistListResultList  = "list"
	DataFilelistListResultTotal = "total"

	// data-filelist-put · payload
	DataFilelistPutPayloadChunks    = "chunks"
	DataFilelistPutPayloadDocIds    = "doc_ids"
	DataFilelistPutPayloadEntries   = "entries"
	DataFilelistPutPayloadIndexedAt = "indexed_at"
	DataFilelistPutPayloadKey       = "key"
	DataFilelistPutPayloadMd5       = "md5"
	DataFilelistPutPayloadMtime     = "mtime"
	DataFilelistPutPayloadPath      = "path"
	DataFilelistPutPayloadSize      = "size"

	// data-filelist-put · result
	DataFilelistPutResultId = "id"
	DataFilelistPutResultOk = "ok"

	// data-filelist-del · payload
	DataFilelistDelPayloadKeys = "keys"

	// data-filelist-del · result
	DataFilelistDelResultDeleted = "deleted"
	DataFilelistDelResultOk      = "ok"

	// config-refresh · event
	ConfigRefreshEventId         = "id"
	ConfigRefreshEventInstanceId = "instance_id"
	ConfigRefreshEventList       = "list"
	ConfigRefreshEventOp         = "op"

	// data-session-list · payload
	DataSessionListPayloadFilter = "filter"

	// data-session-list · result
	DataSessionListResultList = "list"

	// data-session-get · payload
	DataSessionGetPayloadId = "id"

	// data-session-get · result
	DataSessionGetResultData = "data"

	// data-session-history · payload
	DataSessionHistoryPayloadBeforeTurnId   = "before_turn_id"
	DataSessionHistoryPayloadSessionId      = "session_id"
	DataSessionHistoryPayloadTargetBytes    = "target_bytes"
	DataSessionHistoryPayloadTargetMessages = "target_messages"

	// data-session-history · result
	DataSessionHistoryResultMessages = "messages"

	// data-session-content · payload
	DataSessionContentPayloadId        = "id"
	DataSessionContentPayloadKeys      = "keys"
	DataSessionContentPayloadSessionId = "session_id"

	// data-session-content · result
	DataSessionContentResultContents = "contents"

	// data-session-latest · result
	DataSessionLatestResultSessionId = "session_id"

	// data-session-title · payload
	DataSessionTitlePayloadId    = "id"
	DataSessionTitlePayloadTitle = "title"

	// data-session-title · result
	DataSessionTitleResultOk = "ok"

	// data-session-title-changed · event
	DataSessionTitleChangedEventSessionId = "session_id"
	DataSessionTitleChangedEventTitle     = "title"

	// data-session-delete · payload
	DataSessionDeletePayloadId = "id"

	// data-session-delete · result
	DataSessionDeleteResultOk = "ok"

	// data-session-active-set · payload
	DataSessionActiveSetPayloadSessionId = "session_id"

	// data-session-active-set · result
	DataSessionActiveSetResultOk = "ok"

	// data-session-active-get · result
	DataSessionActiveGetResultSessionId = "session_id"

	// data-session-ensure-session · payload
	DataSessionEnsureSessionPayloadParentSessionId = "parent_session_id"
	DataSessionEnsureSessionPayloadSessionId       = "session_id"

	// data-session-ensure-session · result
	DataSessionEnsureSessionResultOk = "ok"

	// data-session-ensure-turn · payload
	DataSessionEnsureTurnPayloadSessionId = "session_id"
	DataSessionEnsureTurnPayloadTurnId    = "turn_id"

	// data-session-ensure-turn · result
	DataSessionEnsureTurnResultOk = "ok"

	// data-session-append-message · payload
	DataSessionAppendMessagePayloadKey    = "key"
	DataSessionAppendMessagePayloadMsg    = "msg"
	DataSessionAppendMessagePayloadTurnId = "turn_id"

	// data-session-append-message · result
	DataSessionAppendMessageResultId = "id"
	DataSessionAppendMessageResultOk = "ok"

	// data-session-set-summary · payload
	DataSessionSetSummaryPayloadSummary = "summary"
	DataSessionSetSummaryPayloadTurnId  = "turn_id"

	// data-session-set-summary · result
	DataSessionSetSummaryResultOk = "ok"

	// data-session-complete-turn · payload
	DataSessionCompleteTurnPayloadBriefTokens  = "brief_tokens"
	DataSessionCompleteTurnPayloadFinishReason = "finish_reason"
	DataSessionCompleteTurnPayloadFullTokens   = "full_tokens"
	DataSessionCompleteTurnPayloadStatus       = "status"
	DataSessionCompleteTurnPayloadTurnId       = "turn_id"

	// data-session-complete-turn · result
	DataSessionCompleteTurnResultOk = "ok"

	// data-session-cleanup-stale · result
	DataSessionCleanupStaleResultCount = "count"
	DataSessionCleanupStaleResultOk    = "ok"

	// data-session-load-messages · payload
	DataSessionLoadMessagesPayloadTurnId = "turn_id"

	// data-session-load-messages · result
	DataSessionLoadMessagesResultMessages = "messages"

	// data-session-context · payload
	DataSessionContextPayloadExcludeTurn     = "exclude_turn"
	DataSessionContextPayloadIncludeSnapshot = "include_snapshot"
	DataSessionContextPayloadSessionId       = "session_id"

	// data-session-context · result
	DataSessionContextResultMessages   = "messages"
	DataSessionContextResultTurnTokens = "turn_tokens"

	// data-snapshot-get · payload
	DataSnapshotGetPayloadSessionId = "session_id"

	// data-snapshot-get · result
	DataSnapshotGetResultSnapshot = "snapshot"

	// data-snapshot-set · payload
	DataSnapshotSetPayloadSessionId = "session_id"
	DataSnapshotSetPayloadSnapshot  = "snapshot"

	// data-snapshot-set · result
	DataSnapshotSetResultOk = "ok"

	// data-knowledge-root · payload
	DataKnowledgeRootPayloadKind = "kind"

	// data-knowledge-root · result
	DataKnowledgeRootResultKind = "kind"
	DataKnowledgeRootResultRoot = "root"

	// data-knowledge-list · payload
	DataKnowledgeListPayloadDir = "dir"

	// data-knowledge-list · result
	DataKnowledgeListResultDir   = "dir"
	DataKnowledgeListResultDirs  = "dirs"
	DataKnowledgeListResultFiles = "files"

	// data-knowledge-read · payload
	DataKnowledgeReadPayloadPath = "path"

	// data-knowledge-read · result
	DataKnowledgeReadResultDoc    = "doc"
	DataKnowledgeReadResultSource = "source"

	// data-knowledge-save · payload
	DataKnowledgeSavePayloadDoc  = "doc"
	DataKnowledgeSavePayloadPath = "path"

	// data-knowledge-save · result
	DataKnowledgeSaveResultOk = "ok"

	// data-knowledge-create · payload
	DataKnowledgeCreatePayloadDir  = "dir"
	DataKnowledgeCreatePayloadName = "name"
	DataKnowledgeCreatePayloadType = "type"

	// data-knowledge-create · result
	DataKnowledgeCreateResultOk   = "ok"
	DataKnowledgeCreateResultPath = "path"

	// data-knowledge-delete · payload
	DataKnowledgeDeletePayloadPath = "path"

	// data-knowledge-delete · result
	DataKnowledgeDeleteResultOk = "ok"

	// data-knowledge-rename · payload
	DataKnowledgeRenamePayloadNewName = "new_name"
	DataKnowledgeRenamePayloadPath    = "path"

	// data-knowledge-rename · result
	DataKnowledgeRenameResultOk = "ok"

	// data-knowledge-mkdir · payload
	DataKnowledgeMkdirPayloadName   = "name"
	DataKnowledgeMkdirPayloadParent = "parent"

	// data-knowledge-mkdir · result
	DataKnowledgeMkdirResultOk   = "ok"
	DataKnowledgeMkdirResultPath = "path"

	// data-knowledge-rmdir · payload
	DataKnowledgeRmdirPayloadPath = "path"

	// data-knowledge-rmdir · result
	DataKnowledgeRmdirResultOk = "ok"

	// data-knowledge-rename-dir · payload
	DataKnowledgeRenameDirPayloadNewName = "new_name"
	DataKnowledgeRenameDirPayloadPath    = "path"

	// data-knowledge-rename-dir · result
	DataKnowledgeRenameDirResultOk = "ok"

	// data-tasktree-list · payload
	DataTasktreeListPayloadIncludeClosed = "include_closed"
	DataTasktreeListPayloadMode          = "mode"
	DataTasktreeListPayloadTopSession    = "top_session"

	// data-tasktree-list · result
	DataTasktreeListResultNodes = "nodes"

	// data-tasktree-tasks · payload
	DataTasktreeTasksPayloadIncludeClosed = "include_closed"
	DataTasktreeTasksPayloadSessionId     = "session_id"
	DataTasktreeTasksPayloadTopSession    = "top_session"

	// data-tasktree-tasks · result
	DataTasktreeTasksResultList = "list"

	// data-tasktree-delete · payload
	DataTasktreeDeletePayloadNodeId = "node_id"

	// data-tasktree-delete · result
	DataTasktreeDeleteResultOk = "ok"

	// data-tasktree-upsert · payload
	DataTasktreeUpsertPayloadArgsDigest   = "args_digest"
	DataTasktreeUpsertPayloadClosed       = "closed"
	DataTasktreeUpsertPayloadContent      = "content"
	DataTasktreeUpsertPayloadCreatedAt    = "created_at"
	DataTasktreeUpsertPayloadDeletedAt    = "deleted_at"
	DataTasktreeUpsertPayloadDoneAt       = "done_at"
	DataTasktreeUpsertPayloadExecJson     = "exec_json"
	DataTasktreeUpsertPayloadFinishedAt   = "finished_at"
	DataTasktreeUpsertPayloadInstanceId   = "instance_id"
	DataTasktreeUpsertPayloadKind         = "kind"
	DataTasktreeUpsertPayloadParentNodeId = "parent_node_id"
	DataTasktreeUpsertPayloadResultDigest = "result_digest"
	DataTasktreeUpsertPayloadSessionId    = "session_id"
	DataTasktreeUpsertPayloadShadow       = "shadow"
	DataTasktreeUpsertPayloadStartedAt    = "started_at"
	DataTasktreeUpsertPayloadState        = "state"
	DataTasktreeUpsertPayloadStatus       = "status"
	DataTasktreeUpsertPayloadTaskId       = "task_id"
	DataTasktreeUpsertPayloadTitle        = "title"
	DataTasktreeUpsertPayloadToolCallId   = "tool_call_id"
	DataTasktreeUpsertPayloadTopSession   = "top_session"
	DataTasktreeUpsertPayloadWorkDir      = "work_dir"

	// data-tasktree-upsert · result
	DataTasktreeUpsertResultOk = "ok"

	// task-deleted · event
	TaskDeletedEventInstanceId = "instance_id"
	TaskDeletedEventNodeId     = "node_id"

	// data-index-ignored · payload
	DataIndexIgnoredPayloadPaths = "paths"

	// data-index-ignored · result
	DataIndexIgnoredResultCodegraph = "codegraph"
	DataIndexIgnoredResultTruncated = "truncated"
	DataIndexIgnoredResultVfts      = "vfts"

	// instance-claim · payload
	InstanceClaimPayloadUser    = "user"
	InstanceClaimPayloadWorkDir = "work_dir"

	// instance-claim · result
	InstanceClaimResultDataDir    = "data_dir"
	InstanceClaimResultInstanceId = "instance_id"
	InstanceClaimResultWorkDir    = "work_dir"

	// instance-register · event
	InstanceRegisterEventClientType = "client_type"
	InstanceRegisterEventDataDir    = "data_dir"
	InstanceRegisterEventInstanceId = "instance_id"
	InstanceRegisterEventWorkDir    = "work_dir"

	// instance-heartbeat · payload
	InstanceHeartbeatPayloadInstanceId = "instance_id"

	// instance-exit · payload
	InstanceExitPayloadInstanceId = "instance_id"

	// llm-start · payload
	LlmStartPayloadContinue   = "continue"
	LlmStartPayloadEffort     = "effort"
	LlmStartPayloadLlm        = "llm"
	LlmStartPayloadScenarioId = "scenario_id"
	LlmStartPayloadSession    = "session"
	LlmStartPayloadThink      = "think"
	LlmStartPayloadTurn       = "turn"

	// llm-start · result
	LlmStartResultAccepted = "accepted"
	LlmStartResultSession  = "session"
	LlmStartResultTurn     = "turn"

	// llm-send · payload
	LlmSendPayloadContent    = "content"
	LlmSendPayloadSession    = "session"
	LlmSendPayloadToolCallId = "tool_call_id"
	LlmSendPayloadTurn       = "turn"
	LlmSendPayloadType       = "type"

	// llm-cancel · payload
	LlmCancelPayloadSession = "session"
	LlmCancelPayloadTurn    = "turn"

	// llm-cancel · result
	LlmCancelResultCancelled = "cancelled"
	LlmCancelResultTurn      = "turn"

	// ask-user-reply · payload
	AskUserReplyPayloadAnswers = "answers"
	AskUserReplyPayloadAskId   = "ask_id"

	// tool-retry · payload
	ToolRetryPayloadInstanceId = "instance_id"
	ToolRetryPayloadSession    = "session"
	ToolRetryPayloadTaskId     = "task_id"
	ToolRetryPayloadToolCallId = "tool_call_id"
	ToolRetryPayloadTurn       = "turn"

	// tool-retry · result
	ToolRetryResultOk     = "ok"
	ToolRetryResultTaskId = "task_id"

	// task-stop · payload
	TaskStopPayloadCascade    = "cascade"
	TaskStopPayloadTaskId     = "task_id"
	TaskStopPayloadToolCallId = "tool_call_id"

	// task-stop · result
	TaskStopResultCancelled = "cancelled"
	TaskStopResultTaskId    = "task_id"

	// task-background · payload
	TaskBackgroundPayloadToolCallId = "tool_call_id"

	// task-background · result
	TaskBackgroundResultTaskId = "task_id"

	// prompt-optimise · payload
	PromptOptimisePayloadPrompt  = "prompt"
	PromptOptimisePayloadTitle   = "title"
	PromptOptimisePayloadUseCase = "useCase"

	// prompt-optimise · result
	PromptOptimiseResultOk = "ok"

	// task-verify · payload
	TaskVerifyPayloadIncludeClosed = "include_closed"
	TaskVerifyPayloadInstanceId    = "instance_id"
	TaskVerifyPayloadTopSession    = "top_session"

	// task-verify · result
	TaskVerifyResultCachedRows          = "cached_rows"
	TaskVerifyResultDiffs               = "diffs"
	TaskVerifyResultError               = "error"
	TaskVerifyResultMatch               = "match"
	TaskVerifyResultOnlyInAuthoritative = "only_in_authoritative"
	TaskVerifyResultOnlyInLayer         = "only_in_layer"
	TaskVerifyResultRows                = "rows"

	// agent-wizard-probe · payload
	AgentWizardProbePayloadInstanceId = "instance_id"

	// agent-wizard-probe · result
	AgentWizardProbeResultError = "error"
	AgentWizardProbeResultOk    = "ok"
	AgentWizardProbeResultProbe = "probe"

	// agent-wizard-compose · payload
	AgentWizardComposePayloadChoices     = "choices"
	AgentWizardComposePayloadDescription = "description"
	AgentWizardComposePayloadInstanceId  = "instance_id"
	AgentWizardComposePayloadMode        = "mode"
	AgentWizardComposePayloadProbe       = "probe"
	AgentWizardComposePayloadTeam        = "team"

	// agent-wizard-compose · result
	AgentWizardComposeResultAgents = "agents"
	AgentWizardComposeResultError  = "error"
	AgentWizardComposeResultOk     = "ok"

	// agent-wizard-generate · payload
	AgentWizardGeneratePayloadAgents      = "agents"
	AgentWizardGeneratePayloadConfig      = "config"
	AgentWizardGeneratePayloadDescription = "description"
	AgentWizardGeneratePayloadInitGit     = "init_git"
	AgentWizardGeneratePayloadInstanceId  = "instance_id"
	AgentWizardGeneratePayloadMemory      = "memory"
	AgentWizardGeneratePayloadProjectSpec = "project_spec"
	AgentWizardGeneratePayloadScenarioId  = "scenario_id"
	AgentWizardGeneratePayloadSceneName   = "scene_name"

	// agent-wizard-generate · result
	AgentWizardGenerateResultConfigSaved    = "config_saved"
	AgentWizardGenerateResultError          = "error"
	AgentWizardGenerateResultErrors         = "errors"
	AgentWizardGenerateResultGitInitialized = "git_initialized"
	AgentWizardGenerateResultMemorySaved    = "memory_saved"
	AgentWizardGenerateResultOk             = "ok"
	AgentWizardGenerateResultScenarioId     = "scenario_id"
	AgentWizardGenerateResultSpecPath       = "spec_path"

	// agent-wizard-skip · payload
	AgentWizardSkipPayloadInstanceId = "instance_id"

	// agent-wizard-skip · result
	AgentWizardSkipResultOk = "ok"

	// llm-simple · payload
	LlmSimplePayloadInstanceId = "instance_id"
	LlmSimplePayloadLlm        = "llm"
	LlmSimplePayloadPrompt     = "prompt"
	LlmSimplePayloadSystem     = "system"

	// llm-simple · result
	LlmSimpleResultText = "text"

	// login-register · payload
	LoginRegisterPayloadPassword = "password"
	LoginRegisterPayloadUsername = "username"

	// login-register · result
	LoginRegisterResultOk   = "ok"
	LoginRegisterResultUser = "user"

	// login-in · payload
	LoginInPayloadPassword = "password"
	LoginInPayloadUsername = "username"

	// login-in · result
	LoginInResultOk   = "ok"
	LoginInResultUser = "user"

	// login-out · result
	LoginOutResultOk = "ok"

	// session-receive · event
	SessionReceiveEventInstanceId = "instance_id"
	SessionReceiveEventPayload    = "payload"
	SessionReceiveEventSession    = "session"
	SessionReceiveEventTurn       = "turn"
	SessionReceiveEventType       = "type"

	// session-complete · event
	SessionCompleteEventCode         = "code"
	SessionCompleteEventFinishReason = "finish_reason"
	SessionCompleteEventInstanceId   = "instance_id"
	SessionCompleteEventMessage      = "message"
	SessionCompleteEventParents      = "parents"
	SessionCompleteEventRetryable    = "retryable"
	SessionCompleteEventSession      = "session"
	SessionCompleteEventStatus       = "status"
	SessionCompleteEventText         = "text"
	SessionCompleteEventTurn         = "turn"

	// session-compress · event
	SessionCompressEventInstanceId      = "instance_id"
	SessionCompressEventLastTurn        = "last_turn"
	SessionCompressEventMaxContextToken = "max_context_token"
	SessionCompressEventMaxOutputToken  = "max_output_token"
	SessionCompressEventSession         = "session"
	SessionCompressEventSnapshotTurn    = "snapshot_turn"

	// session-ask · event
	SessionAskEventAskId      = "ask_id"
	SessionAskEventExpiresAt  = "expires_at"
	SessionAskEventInstanceId = "instance_id"
	SessionAskEventQuestions  = "questions"
	SessionAskEventSession    = "session"
	SessionAskEventTurn       = "turn"

	// session-turn-start · event
	SessionTurnStartEventInstanceId = "instance_id"
	SessionTurnStartEventParents    = "parents"
	SessionTurnStartEventSession    = "session"
	SessionTurnStartEventTurn       = "turn"

	// session-new · event
	SessionNewEventInstanceId      = "instance_id"
	SessionNewEventParentSessionId = "parent_session_id"
	SessionNewEventSessionId       = "session_id"

	// task-started · event
	TaskStartedEventArgs    = "args"
	TaskStartedEventKind    = "kind"
	TaskStartedEventSession = "session"
	TaskStartedEventState   = "state"
	TaskStartedEventTaskId  = "task_id"
	TaskStartedEventTool    = "tool"
	TaskStartedEventTurn    = "turn"
	TaskStartedEventWorkDir = "work_dir"

	// task-updated · event
	TaskUpdatedEventArgs    = "args"
	TaskUpdatedEventKind    = "kind"
	TaskUpdatedEventSession = "session"
	TaskUpdatedEventState   = "state"
	TaskUpdatedEventTaskId  = "task_id"
	TaskUpdatedEventTool    = "tool"
	TaskUpdatedEventTurn    = "turn"
	TaskUpdatedEventWorkDir = "work_dir"

	// task-done · event
	TaskDoneEventArgs    = "args"
	TaskDoneEventKind    = "kind"
	TaskDoneEventSession = "session"
	TaskDoneEventState   = "state"
	TaskDoneEventTaskId  = "task_id"
	TaskDoneEventTool    = "tool"
	TaskDoneEventTurn    = "turn"
	TaskDoneEventWorkDir = "work_dir"

	// server-starting · event
	ServerStartingEventStartedAt = "started_at"

	// prompt-optimised · event
	PromptOptimisedEventContent    = "content"
	PromptOptimisedEventError      = "error"
	PromptOptimisedEventInstanceId = "instance_id"
	PromptOptimisedEventType       = "type"

	// tool-notify · event
	ToolNotifyEventInstanceId = "instance_id"
	ToolNotifyEventKind       = "kind"
	ToolNotifyEventMessage    = "message"
	ToolNotifyEventMessageId  = "message_id"
	ToolNotifyEventNotice     = "notice"
	ToolNotifyEventPlugin     = "plugin"
	ToolNotifyEventReason     = "reason"
	ToolNotifyEventSessionId  = "session_id"
	ToolNotifyEventTaskId     = "task_id"
	ToolNotifyEventTurnId     = "turn_id"

	// mcp-tools-list · payload
	McpToolsListPayloadCursor = "cursor"

	// mcp-tools-list · result
	McpToolsListResultResultType = "resultType"
	McpToolsListResultTools      = "tools"
	McpToolsListResultTtlMs      = "ttlMs"

	// mcp-tools-call · payload
	McpToolsCallPayloadArguments = "arguments"
	McpToolsCallPayloadName      = "name"

	// mcp-tools-call · result
	McpToolsCallResultContent           = "content"
	McpToolsCallResultIsError           = "isError"
	McpToolsCallResultResultType        = "resultType"
	McpToolsCallResultStructuredContent = "structuredContent"

	// mcp-tools-wait · payload
	McpToolsWaitPayloadTaskId     = "task_id"
	McpToolsWaitPayloadToolCallId = "tool_call_id"

	// mcp-tools-wait · result
	McpToolsWaitResultTaskId  = "task_id"
	McpToolsWaitResultWaiting = "waiting"

	// mcp-tools-register · payload
	McpToolsRegisterPayloadAsync          = "async"
	McpToolsRegisterPayloadAsyncThreshold = "async_threshold"
	McpToolsRegisterPayloadCategory       = "category"
	McpToolsRegisterPayloadDescription    = "description"
	McpToolsRegisterPayloadHandlerSubject = "handler_subject"
	McpToolsRegisterPayloadHot            = "hot"
	McpToolsRegisterPayloadName           = "name"
	McpToolsRegisterPayloadOwner          = "owner"
	McpToolsRegisterPayloadPreHookSubject = "pre_hook_subject"
	McpToolsRegisterPayloadSchema         = "schema"
	McpToolsRegisterPayloadScope          = "scope"
	McpToolsRegisterPayloadTimeout        = "timeout"

	// mcp-tools-register · result
	McpToolsRegisterResultKind       = "kind"
	McpToolsRegisterResultName       = "name"
	McpToolsRegisterResultRegistered = "registered"

	// mcp-tools-unregister · payload
	McpToolsUnregisterPayloadName  = "name"
	McpToolsUnregisterPayloadScope = "scope"

	// mcp-tools-unregister · result
	McpToolsUnregisterResultKind         = "kind"
	McpToolsUnregisterResultName         = "name"
	McpToolsUnregisterResultUnregistered = "unregistered"

	// mcp-prompts-list · result
	McpPromptsListResultPrompts = "prompts"

	// mcp-prompts-get · payload
	McpPromptsGetPayloadName = "name"

	// mcp-prompts-get · result
	McpPromptsGetResultArguments   = "arguments"
	McpPromptsGetResultContent     = "content"
	McpPromptsGetResultDescription = "description"
	McpPromptsGetResultName        = "name"
	McpPromptsGetResultType        = "type"

	// mcp-prompts-register · payload
	McpPromptsRegisterPayloadArguments   = "arguments"
	McpPromptsRegisterPayloadAssetKind   = "asset_kind"
	McpPromptsRegisterPayloadContent     = "content"
	McpPromptsRegisterPayloadDescription = "description"
	McpPromptsRegisterPayloadName        = "name"
	McpPromptsRegisterPayloadPath        = "path"
	McpPromptsRegisterPayloadScope       = "scope"

	// mcp-prompts-register · result
	McpPromptsRegisterResultKind       = "kind"
	McpPromptsRegisterResultName       = "name"
	McpPromptsRegisterResultRegistered = "registered"

	// mcp-prompts-unregister · payload
	McpPromptsUnregisterPayloadAssetKind = "asset_kind"
	McpPromptsUnregisterPayloadName      = "name"
	McpPromptsUnregisterPayloadScope     = "scope"

	// mcp-prompts-unregister · result
	McpPromptsUnregisterResultKind         = "kind"
	McpPromptsUnregisterResultName         = "name"
	McpPromptsUnregisterResultUnregistered = "unregistered"

	// mcp-resources-list · result
	McpResourcesListResultResources = "resources"

	// mcp-resources-read · payload
	McpResourcesReadPayloadUri = "uri"

	// mcp-resources-read · result
	McpResourcesReadResultResource = "resource"

	// mcp-resources-register · payload
	McpResourcesRegisterPayloadContent     = "content"
	McpResourcesRegisterPayloadDescription = "description"
	McpResourcesRegisterPayloadMimetype    = "mimetype"
	McpResourcesRegisterPayloadName        = "name"
	McpResourcesRegisterPayloadPath        = "path"
	McpResourcesRegisterPayloadScope       = "scope"
	McpResourcesRegisterPayloadUri         = "uri"

	// mcp-resources-register · result
	McpResourcesRegisterResultKind       = "kind"
	McpResourcesRegisterResultName       = "name"
	McpResourcesRegisterResultRegistered = "registered"

	// mcp-resources-unregister · payload
	McpResourcesUnregisterPayloadName  = "name"
	McpResourcesUnregisterPayloadScope = "scope"

	// mcp-resources-unregister · result
	McpResourcesUnregisterResultKind         = "kind"
	McpResourcesUnregisterResultName         = "name"
	McpResourcesUnregisterResultUnregistered = "unregistered"

	// mcp-servers-list · payload
	McpServersListPayloadServer = "server"

	// mcp-servers-list · result
	McpServersListResultServers = "servers"

	// mcp-servers-get · payload
	McpServersGetPayloadServer = "server"

	// mcp-servers-get · result
	McpServersGetResultServer = "server"

	// mcp-servers-register · payload
	McpServersRegisterPayloadMcpServer = "mcp_server"
	McpServersRegisterPayloadName      = "name"
	McpServersRegisterPayloadNamespace = "namespace"
	McpServersRegisterPayloadOrigin    = "origin"
	McpServersRegisterPayloadScope     = "scope"
	McpServersRegisterPayloadTransport = "transport"
	McpServersRegisterPayloadUrl       = "url"

	// mcp-servers-register · result
	McpServersRegisterResultName       = "name"
	McpServersRegisterResultRegistered = "registered"

	// mcp-servers-unregister · payload
	McpServersUnregisterPayloadName  = "name"
	McpServersUnregisterPayloadScope = "scope"

	// mcp-servers-unregister · result
	McpServersUnregisterResultName         = "name"
	McpServersUnregisterResultUnregistered = "unregistered"

	// mcp-gateway-check · result
	McpGatewayCheckResultOk      = "ok"
	McpGatewayCheckResultServers = "servers"
	McpGatewayCheckResultTools   = "tools"

	// mcp-gateway-reload · result
	McpGatewayReloadResultRefreshed    = "refreshed"
	McpGatewayReloadResultReloaded     = "reloaded"
	McpGatewayReloadResultRemovedTools = "removed_tools"

	// mcp-tasks-report · event
	McpTasksReportEventInstanceId    = "instance_id"
	McpTasksReportEventParent        = "parent"
	McpTasksReportEventResultSummary = "result_summary"
	McpTasksReportEventSession       = "session"
	McpTasksReportEventState         = "state"
	McpTasksReportEventTaskId        = "task_id"
	McpTasksReportEventTool          = "tool"
	McpTasksReportEventToolCallId    = "tool_call_id"
	McpTasksReportEventTopSession    = "top_session"
	McpTasksReportEventTurn          = "turn"

	// mcp-tools-timeout · event
	McpToolsTimeoutEventInstanceId = "instance_id"
	McpToolsTimeoutEventOptions    = "options"
	McpToolsTimeoutEventReason     = "reason"
	McpToolsTimeoutEventTaskId     = "task_id"
	McpToolsTimeoutEventTimeoutS   = "timeout_s"
	McpToolsTimeoutEventTool       = "tool"
	McpToolsTimeoutEventToolCallId = "tool_call_id"

	// mcp-gateway-changed · event
	McpGatewayChangedEventInstanceId = "instance_id"
	McpGatewayChangedEventKind       = "kind"
	McpGatewayChangedEventName       = "name"
	McpGatewayChangedEventStatus     = "status"

	// history-pre-tool-hook · payload
	HistoryPreToolHookPayloadContext    = "context"
	HistoryPreToolHookPayloadTool       = "tool"
	HistoryPreToolHookPayloadTouchFiles = "touch_files"

	// codegraph-tool-call · payload
	CodegraphToolCallPayloadArgs    = "args"
	CodegraphToolCallPayloadContext = "context"
	CodegraphToolCallPayloadTool    = "tool"

	// codegraph-tool-call · result
	CodegraphToolCallResultContent    = "content"
	CodegraphToolCallResultIsError    = "isError"
	CodegraphToolCallResultResultType = "resultType"

	// vfts-tool-call · payload
	VftsToolCallPayloadArgs    = "args"
	VftsToolCallPayloadContext = "context"
	VftsToolCallPayloadTool    = "tool"

	// vfts-tool-call · result
	VftsToolCallResultContent    = "content"
	VftsToolCallResultIsError    = "isError"
	VftsToolCallResultResultType = "resultType"

	// vfts.dict.get · payload
	VftsDictGetPayloadInstanceId = "instance_id"

	// vfts.dict.get · result
	VftsDictGetResultBaseDicts    = "base_dicts"
	VftsDictGetResultDictDir      = "dict_dir"
	VftsDictGetResultError        = "error"
	VftsDictGetResultOk           = "ok"
	VftsDictGetResultUserDict     = "user_dict"
	VftsDictGetResultUserDictPath = "user_dict_path"
	VftsDictGetResultWordCount    = "word_count"

	// vfts.dict.set · payload
	VftsDictSetPayloadInstanceId = "instance_id"
	VftsDictSetPayloadUserDict   = "user_dict"

	// vfts.dict.set · result
	VftsDictSetResultError     = "error"
	VftsDictSetResultOk        = "ok"
	VftsDictSetResultWordCount = "word_count"

	// vfts.reindex · payload
	VftsReindexPayloadInstanceId = "instance_id"

	// vfts.reindex · result
	VftsReindexResultOk      = "ok"
	VftsReindexResultStarted = "started"

	// project-config-open · payload
	ProjectConfigOpenPayloadTab = "tab"

	// preview-tab-open · payload
	PreviewTabOpenPayloadKind  = "kind"
	PreviewTabOpenPayloadTab   = "tab"
	PreviewTabOpenPayloadTitle = "title"
)

// ── 通用字段常量（全部字段名并集，跨主题共用；镜像 JS FieldKeys）──
const (
	FieldAccepted            = "accepted"
	FieldActivated           = "activated"
	FieldAgents              = "agents"
	FieldAnswers             = "answers"
	FieldApiKey              = "apiKey"
	FieldArgs                = "args"
	FieldArgsDigest          = "args_digest"
	FieldArguments           = "arguments"
	FieldAskId               = "ask_id"
	FieldAssetKind           = "asset_kind"
	FieldAsync               = "async"
	FieldAsyncThreshold      = "async_threshold"
	FieldB64                 = "b64"
	FieldBaseDicts           = "base_dicts"
	FieldBaseUrl             = "baseUrl"
	FieldBeforeTurnId        = "before_turn_id"
	FieldBriefTokens         = "brief_tokens"
	FieldCachedRows          = "cached_rows"
	FieldCancelled           = "cancelled"
	FieldCascade             = "cascade"
	FieldCategory            = "category"
	FieldChildren            = "children"
	FieldChoices             = "choices"
	FieldChunks              = "chunks"
	FieldClientType          = "client_type"
	FieldClosed              = "closed"
	FieldCode                = "code"
	FieldCodegraph           = "codegraph"
	FieldCommand             = "command"
	FieldConfig              = "config"
	FieldConfigSaved         = "config_saved"
	FieldContent             = "content"
	FieldContents            = "contents"
	FieldContext             = "context"
	FieldContinue            = "continue"
	FieldCount               = "count"
	FieldCreatedAt           = "created_at"
	FieldCursor              = "cursor"
	FieldData                = "data"
	FieldDataDir             = "data_dir"
	FieldDeleted             = "deleted"
	FieldDeletedAt           = "deleted_at"
	FieldDescription         = "description"
	FieldDestDir             = "dest_dir"
	FieldDictDir             = "dict_dir"
	FieldDiffs               = "diffs"
	FieldDir                 = "dir"
	FieldDirs                = "dirs"
	FieldDoc                 = "doc"
	FieldDocIds              = "doc_ids"
	FieldDoneAt              = "done_at"
	FieldEffort              = "effort"
	FieldEntries             = "entries"
	FieldError               = "error"
	FieldErrors              = "errors"
	FieldExcludeTurn         = "exclude_turn"
	FieldExecJson            = "exec_json"
	FieldExpandedKeys        = "expandedKeys"
	FieldExpiresAt           = "expires_at"
	FieldFileId              = "file_id"
	FieldFiles               = "files"
	FieldFiletree            = "filetree"
	FieldFiletreeWidth       = "filetreeWidth"
	FieldFilter              = "filter"
	FieldFinishReason        = "finish_reason"
	FieldFinishedAt          = "finished_at"
	FieldFullTokens          = "full_tokens"
	FieldGit                 = "git"
	FieldGitInitialized      = "git_initialized"
	FieldGitInstalled        = "gitInstalled"
	FieldGroups              = "groups"
	FieldHandlerSubject      = "handler_subject"
	FieldHot                 = "hot"
	FieldId                  = "id"
	FieldIds                 = "ids"
	FieldIncludeClosed       = "include_closed"
	FieldIncludeSnapshot     = "include_snapshot"
	FieldIndexedAt           = "indexed_at"
	FieldInitGit             = "init_git"
	FieldInstanceId          = "instance_id"
	FieldIsDir               = "is_dir"
	FieldIsError             = "isError"
	FieldKey                 = "key"
	FieldKeys                = "keys"
	FieldKind                = "kind"
	FieldLastTurn            = "last_turn"
	FieldLatencyMs           = "latency_ms"
	FieldLayout              = "layout"
	FieldLevel               = "level"
	FieldLimit               = "limit"
	FieldList                = "list"
	FieldLlm                 = "llm"
	FieldLogDir              = "logDir"
	FieldMatch               = "match"
	FieldMaxContextToken     = "max_context_token"
	FieldMaxOutputToken      = "max_output_token"
	FieldMaximized           = "maximized"
	FieldMcpServer           = "mcp_server"
	FieldMcpServers          = "mcpServers"
	FieldMd5                 = "md5"
	FieldMemory              = "memory"
	FieldMemorySaved         = "memory_saved"
	FieldMessage             = "message"
	FieldMessageId           = "message_id"
	FieldMessages            = "messages"
	FieldMimetype            = "mimetype"
	FieldMinimized           = "minimized"
	FieldMode                = "mode"
	FieldModel               = "model"
	FieldModelEcho           = "model_echo"
	FieldMsg                 = "msg"
	FieldMtime               = "mtime"
	FieldName                = "name"
	FieldNamespace           = "namespace"
	FieldNewName             = "new_name"
	FieldNodeId              = "node_id"
	FieldNodes               = "nodes"
	FieldNotice              = "notice"
	FieldOffset              = "offset"
	FieldOk                  = "ok"
	FieldOldLevel            = "old_level"
	FieldOldName             = "old_name"
	FieldOnlyInAuthoritative = "only_in_authoritative"
	FieldOnlyInLayer         = "only_in_layer"
	FieldOp                  = "op"
	FieldOpenedFile          = "openedFile"
	FieldOpenedFiles         = "opened_files"
	FieldOperation           = "operation"
	FieldOptions             = "options"
	FieldOrigin              = "origin"
	FieldOverwrite           = "overwrite"
	FieldOwner               = "owner"
	FieldParent              = "parent"
	FieldParentNodeId        = "parent_node_id"
	FieldParentSessionId     = "parent_session_id"
	FieldParents             = "parents"
	FieldPassword            = "password"
	FieldPath                = "path"
	FieldPaths               = "paths"
	FieldPayload             = "payload"
	FieldPlugin              = "plugin"
	FieldPreHookSubject      = "pre_hook_subject"
	FieldPrefix              = "prefix"
	FieldProbe               = "probe"
	FieldProjectSpec         = "project_spec"
	FieldPrompt              = "prompt"
	FieldPrompts             = "prompts"
	FieldProtocol            = "protocol"
	FieldQuery               = "query"
	FieldQuestions           = "questions"
	FieldQueued              = "queued"
	FieldReason              = "reason"
	FieldRecursive           = "recursive"
	FieldRefreshed           = "refreshed"
	FieldRegistered          = "registered"
	FieldReloaded            = "reloaded"
	FieldRemovedTools        = "removed_tools"
	FieldResource            = "resource"
	FieldResources           = "resources"
	FieldResultDigest        = "result_digest"
	FieldResultSummary       = "result_summary"
	FieldResultType          = "resultType"
	FieldResults             = "results"
	FieldRetryable           = "retryable"
	FieldRoot                = "root"
	FieldRows                = "rows"
	FieldScenarioId          = "scenario_id"
	FieldSceneName           = "scene_name"
	FieldSchema              = "schema"
	FieldScope               = "scope"
	FieldSelectedKey         = "selectedKey"
	FieldServer              = "server"
	FieldServers             = "servers"
	FieldSession             = "session"
	FieldSessionId           = "session_id"
	FieldShadow              = "shadow"
	FieldSize                = "size"
	FieldSnapshot            = "snapshot"
	FieldSnapshotTurn        = "snapshot_turn"
	FieldSource              = "source"
	FieldSpecPath            = "spec_path"
	FieldStart               = "start"
	FieldStarted             = "started"
	FieldStartedAt           = "started_at"
	FieldState               = "state"
	FieldStatus              = "status"
	FieldStructuredContent   = "structuredContent"
	FieldSummary             = "summary"
	FieldSvn                 = "svn"
	FieldSystem              = "system"
	FieldTab                 = "tab"
	FieldTargetBytes         = "target_bytes"
	FieldTargetMessages      = "target_messages"
	FieldTaskId              = "task_id"
	FieldTeam                = "team"
	FieldText                = "text"
	FieldThink               = "think"
	FieldTimeout             = "timeout"
	FieldTimeoutS            = "timeout_s"
	FieldTitle               = "title"
	FieldTool                = "tool"
	FieldToolCallId          = "tool_call_id"
	FieldTools               = "tools"
	FieldTopSession          = "top_session"
	FieldTotal               = "total"
	FieldTouchFiles          = "touch_files"
	FieldTransport           = "transport"
	FieldTreeData            = "treeData"
	FieldTruncated           = "truncated"
	FieldTtlMs               = "ttlMs"
	FieldTurn                = "turn"
	FieldTurnId              = "turn_id"
	FieldTurnTokens          = "turn_tokens"
	FieldType                = "type"
	FieldUi                  = "ui"
	FieldUnregistered        = "unregistered"
	FieldUri                 = "uri"
	FieldUrl                 = "url"
	FieldUseCase             = "useCase"
	FieldUser                = "user"
	FieldUserDict            = "user_dict"
	FieldUserDictPath        = "user_dict_path"
	FieldUsername            = "username"
	FieldVfts                = "vfts"
	FieldWaiting             = "waiting"
	FieldWindow              = "window"
	FieldWindowId            = "window_id"
	FieldWindows             = "windows"
	FieldWizardRequired      = "wizard_required"
	FieldWordCount           = "word_count"
	FieldWorkDir             = "work_dir"
)
