// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {fileversions} from '../models';

export function AnalyzeProject():Promise<Record<string, any>>;

export function ApplyScenario(arg1:main.applyScenarioArgs):Promise<void>;

export function CancelChat(arg1:main.cancelChatArgs):Promise<void>;

export function ClearCodebaseIndex():Promise<void>;

export function CreateDirInDir(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateFileInDir(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateSession(arg1:main.createSessionArgs):Promise<Record<string, any>>;

export function DeleteFilePath(arg1:string):Promise<Record<string, any>>;

export function DeleteNote(arg1:string):Promise<Record<string, any>>;

export function DeleteScenario(arg1:main.deleteScenarioArgs):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DiscoverMCPServerTools(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DuplicateFile(arg1:string):Promise<Record<string, any>>;

export function GeneratePrompts(arg1:Record<string, any>):Promise<void>;

export function GetActiveScenario():Promise<Record<string, any>>;

export function GetAllConfig():Promise<Record<string, any>>;

export function GetChromeStatus():Promise<Record<string, any>>;

export function GetCodebaseIndexStatus():Promise<Record<string, any>>;

export function GetConfig(arg1:string):Promise<Record<string, string>>;

export function GetFileTree(arg1:string):Promise<Record<string, any>>;

export function GetFileTreeChildren(arg1:string):Promise<Record<string, any>>;

export function GetFileVersions(arg1:string):Promise<Array<fileversions.VersionRecord>>;

export function GetHttpPort():Promise<number>;

export function GetLatestSessionID():Promise<Record<string, any>>;

export function GetMessageContent(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function GetNote(arg1:string):Promise<Record<string, any>>;

export function GetNotes():Promise<Record<string, any>>;

export function GetProjectAgents():Promise<Record<string, any>>;

export function GetProjectSecurity():Promise<Record<string, any>>;

export function GetProjectTools():Promise<Record<string, any>>;

export function GetPrompt(arg1:string):Promise<Record<string, string>>;

export function GetRecentDirs():Promise<Record<string, any>>;

export function GetScenarioList():Promise<Record<string, any>>;

export function GetScenarios():Promise<Record<string, any>>;

export function GetSession(arg1:string):Promise<Record<string, any>>;

export function GetTasksByTurn(arg1:string):Promise<Record<string, any>>;

export function GetTechInfo():Promise<Record<string, any>>;

export function GetTurnsBySession(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function GetUserConfig():Promise<Record<string, any>>;

export function GetVCSInfo():Promise<main.VCSInfo>;

export function GetVersionContent(arg1:number):Promise<fileversions.VersionContent>;

export function GetWorkDir():Promise<string>;

export function ListAllSessions():Promise<Record<string, any>>;

export function ListSessions():Promise<Record<string, any>>;

export function LoadMissingAgentsFromResource():Promise<Record<string, any>>;

export function OpenDevTools():Promise<void>;

export function OpenDir(arg1:string):Promise<Record<string, string>>;

export function OpenDirDialog():Promise<Record<string, string>>;

export function OpenFileDialog(arg1:Record<string, any>):Promise<Record<string, any>>;

export function OpenWithDefault(arg1:string):Promise<Record<string, any>>;

export function OpenWithDialog(arg1:string):Promise<Record<string, any>>;

export function OptimizeAgentPrompt(arg1:Record<string, any>):Promise<void>;

export function PickExecutableFile():Promise<Record<string, any>>;

export function PickFolder():Promise<Record<string, any>>;

export function ReadFileContent(arg1:string,arg2:boolean):Promise<any>;

export function ReindexCodebase():Promise<number>;

export function RenameFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ResetFailedCodebaseIndex():Promise<void>;

export function RespondAskUser(arg1:main.askUserResponse):Promise<Record<string, string>>;

export function RestoreAgent(arg1:number):Promise<Record<string, any>>;

export function RestoreVersion(arg1:number):Promise<void>;

export function RevealInExplorer(arg1:string):Promise<Record<string, any>>;

export function SaveNote(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SaveProjectAgents(arg1:Record<string, any>):Promise<void>;

export function SaveProjectSecurity(arg1:Record<string, any>):Promise<void>;

export function SaveProjectTools(arg1:Record<string, any>):Promise<void>;

export function SaveScenario(arg1:main.saveScenarioArgs):Promise<Record<string, any>>;

export function SaveUserConfig(arg1:Record<string, any>):Promise<void>;

export function SearchProjectFiles(arg1:string):Promise<Array<main.SearchResult>>;

export function SendChatMessage(arg1:main.sendChatArgs):Promise<Record<string, string>>;

export function SetActiveScenario(arg1:number):Promise<void>;

export function SetActiveSession(arg1:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function StartCodebaseIndex():Promise<void>;

export function SubscribeSession(arg1:string):Promise<void>;

export function UnsubscribeSession(arg1:string):Promise<void>;

export function UnwatchDir(arg1:string):Promise<void>;

export function UpdateSessionTitle(arg1:string,arg2:string):Promise<void>;

export function UpdateTaskStatus(arg1:main.updateTaskArgs):Promise<void>;

export function WatchDir(arg1:string):Promise<void>;
