// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeProject() {
  return window['go']['main']['App']['AnalyzeProject']();
}

export function ApplyScenario(arg1) {
  return window['go']['main']['App']['ApplyScenario'](arg1);
}

export function CancelChat(arg1) {
  return window['go']['main']['App']['CancelChat'](arg1);
}

export function ClearCodebaseIndex() {
  return window['go']['main']['App']['ClearCodebaseIndex']();
}

export function CreateDirInDir(arg1, arg2) {
  return window['go']['main']['App']['CreateDirInDir'](arg1, arg2);
}

export function CreateFileInDir(arg1, arg2) {
  return window['go']['main']['App']['CreateFileInDir'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteFilePath(arg1) {
  return window['go']['main']['App']['DeleteFilePath'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteScenario(arg1) {
  return window['go']['main']['App']['DeleteScenario'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DiscoverMCPServerTools(arg1, arg2) {
  return window['go']['main']['App']['DiscoverMCPServerTools'](arg1, arg2);
}

export function DuplicateFile(arg1) {
  return window['go']['main']['App']['DuplicateFile'](arg1);
}

export function GeneratePrompts(arg1) {
  return window['go']['main']['App']['GeneratePrompts'](arg1);
}

export function GetActiveScenario() {
  return window['go']['main']['App']['GetActiveScenario']();
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetChromeStatus() {
  return window['go']['main']['App']['GetChromeStatus']();
}

export function GetCodebaseIndexStatus() {
  return window['go']['main']['App']['GetCodebaseIndexStatus']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetFileTreeChildren(arg1) {
  return window['go']['main']['App']['GetFileTreeChildren'](arg1);
}

export function GetFileVersions(arg1) {
  return window['go']['main']['App']['GetFileVersions'](arg1);
}

export function GetHttpPort() {
  return window['go']['main']['App']['GetHttpPort']();
}

export function GetLatestSessionID() {
  return window['go']['main']['App']['GetLatestSessionID']();
}

export function GetMessageContent(arg1, arg2) {
  return window['go']['main']['App']['GetMessageContent'](arg1, arg2);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetProjectAgents() {
  return window['go']['main']['App']['GetProjectAgents']();
}

export function GetProjectSecurity() {
  return window['go']['main']['App']['GetProjectSecurity']();
}

export function GetProjectTools() {
  return window['go']['main']['App']['GetProjectTools']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetRecentDirs() {
  return window['go']['main']['App']['GetRecentDirs']();
}

export function GetScenarioList() {
  return window['go']['main']['App']['GetScenarioList']();
}

export function GetScenarios() {
  return window['go']['main']['App']['GetScenarios']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetTasksByTurn(arg1) {
  return window['go']['main']['App']['GetTasksByTurn'](arg1);
}

export function GetTechInfo() {
  return window['go']['main']['App']['GetTechInfo']();
}

export function GetTurnsBySession(arg1, arg2) {
  return window['go']['main']['App']['GetTurnsBySession'](arg1, arg2);
}

export function GetUserConfig() {
  return window['go']['main']['App']['GetUserConfig']();
}

export function GetVCSInfo() {
  return window['go']['main']['App']['GetVCSInfo']();
}

export function GetVersionContent(arg1) {
  return window['go']['main']['App']['GetVersionContent'](arg1);
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ListAllSessions() {
  return window['go']['main']['App']['ListAllSessions']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadMissingAgentsFromResource() {
  return window['go']['main']['App']['LoadMissingAgentsFromResource']();
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenDirDialog() {
  return window['go']['main']['App']['OpenDirDialog']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenWithDefault(arg1) {
  return window['go']['main']['App']['OpenWithDefault'](arg1);
}

export function OpenWithDialog(arg1) {
  return window['go']['main']['App']['OpenWithDialog'](arg1);
}

export function OptimizeAgentPrompt(arg1) {
  return window['go']['main']['App']['OptimizeAgentPrompt'](arg1);
}

export function PickExecutableFile() {
  return window['go']['main']['App']['PickExecutableFile']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function ReadFileContent(arg1, arg2) {
  return window['go']['main']['App']['ReadFileContent'](arg1, arg2);
}

export function ReindexCodebase() {
  return window['go']['main']['App']['ReindexCodebase']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResetFailedCodebaseIndex() {
  return window['go']['main']['App']['ResetFailedCodebaseIndex']();
}

export function RespondAskUser(arg1) {
  return window['go']['main']['App']['RespondAskUser'](arg1);
}

export function RestoreAgent(arg1) {
  return window['go']['main']['App']['RestoreAgent'](arg1);
}

export function RestoreVersion(arg1) {
  return window['go']['main']['App']['RestoreVersion'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveProjectAgents(arg1) {
  return window['go']['main']['App']['SaveProjectAgents'](arg1);
}

export function SaveProjectSecurity(arg1) {
  return window['go']['main']['App']['SaveProjectSecurity'](arg1);
}

export function SaveProjectTools(arg1) {
  return window['go']['main']['App']['SaveProjectTools'](arg1);
}

export function SaveScenario(arg1) {
  return window['go']['main']['App']['SaveScenario'](arg1);
}

export function SaveUserConfig(arg1) {
  return window['go']['main']['App']['SaveUserConfig'](arg1);
}

export function SearchProjectFiles(arg1) {
  return window['go']['main']['App']['SearchProjectFiles'](arg1);
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SetActiveScenario(arg1) {
  return window['go']['main']['App']['SetActiveScenario'](arg1);
}

export function SetActiveSession(arg1) {
  return window['go']['main']['App']['SetActiveSession'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function StartCodebaseIndex() {
  return window['go']['main']['App']['StartCodebaseIndex']();
}

export function SubscribeSession(arg1) {
  return window['go']['main']['App']['SubscribeSession'](arg1);
}

export function UnsubscribeSession(arg1) {
  return window['go']['main']['App']['UnsubscribeSession'](arg1);
}

export function UnwatchDir(arg1) {
  return window['go']['main']['App']['UnwatchDir'](arg1);
}

export function UpdateSessionTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionTitle'](arg1, arg2);
}

export function UpdateTaskStatus(arg1) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1);
}

export function WatchDir(arg1) {
  return window['go']['main']['App']['WatchDir'](arg1);
}
